[tool.poetry]
name = "weather-and-shmot"
version = "0.1.0"
description = ""
authors = ["Pe7r0v14 <dav1dovpetr@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
